services:
  oracle:
    image: container-registry.oracle.com/database/free:23.4.0.0-lite
    environment:
      ORACLE_PDB: ORCLPDB
      ORACLE_PWD: root
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1522:1521"
    container_name: "oracledb"
    volumes:
      - ./GeneratedDB:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'select 1 from dual' | sqlplus -S PMS/root@localhost:1521/ORCLPDB"
        ]
      interval: 30s
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend/onlineProjectManagment
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: "pms-backend"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      ORACLE_HOST: oracledb

  frontend:
    build:
      context: ./frontend/Project Management System
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - oracle
      - backend
    container_name: "pms-frontend"
