INSERT INTO projects (id, category, department, division, end_date, location, priority, project_name, reason, start_date, status, type) VALUES 
(69, 'Quality A', 'Information Technology', 'Division 1', TO_DATE('2024-07-21', 'YYYY-MM-DD'), 'Pune', 'High', 'Online Project Management', 'Business', TO_DATE('2024-07-11', 'YYYY-MM-DD'), 'Closed', 'Internal'),
(70, 'Quality B', 'Human Resource', 'Division 1', TO_DATE('2024-07-31', 'YYYY-MM-DD'), 'Pune', 'High', 'HR Onboarding System', 'Business', TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'Closed', 'Internal'),
(71, 'Quality B', 'Sales', 'Division 2', TO_DATE('2024-10-24', 'YYYY-MM-DD'), 'Mumbai', 'Medium', 'Sales CRM Integration', 'Dealership', TO_DATE('2024-03-14', 'YYYY-MM-DD'), 'Registered', 'Vendor'),
(72, 'Quality C', 'Finance', 'Division 1', TO_DATE('2024-11-29', 'YYYY-MM-DD'), 'Pune', 'High', 'Financial Reporting Tool', 'Business', TO_DATE('2024-04-26', 'YYYY-MM-DD'), 'Cancelled', 'Internal'),
(73, 'Quality D', 'Information Technology', 'Division 1', TO_DATE('2025-05-28', 'YYYY-MM-DD'), 'Pune', 'Low', 'IT Infrastructure Upgrade', 'Business', TO_DATE('2024-04-12', 'YYYY-MM-DD'), 'Running', 'Internal'),
(74, 'Quality A', 'Legal', 'Division 2', TO_DATE('2025-01-17', 'YYYY-MM-DD'), 'Bangalore', 'Medium', 'Legal Compliance System', 'Business', TO_DATE('2023-12-07', 'YYYY-MM-DD'), 'Registered', 'Vendor'),
(75, 'Quality C', 'Strategy', 'Division 1', TO_DATE('2025-06-19', 'YYYY-MM-DD'), 'Mumbai', 'Low', 'Strategic Planning Dashboard', 'Other', TO_DATE('2023-07-19', 'YYYY-MM-DD'), 'Closed', 'External'),
(76, 'Quality A', 'Quality', 'Division 2', TO_DATE('2024-08-09', 'YYYY-MM-DD'), 'Other', 'High', 'Quality Assurance Automation', 'Transport', TO_DATE('2023-10-07', 'YYYY-MM-DD'), 'Cancelled', 'Vendor'),
(77, 'Quality D', 'Sales', 'Division 1', TO_DATE('2024-07-30', 'YYYY-MM-DD'), 'Mumbai', 'Low', 'Marketing Campaign Management', 'Transport', TO_DATE('2024-07-03', 'YYYY-MM-DD'), 'Running', 'External'),
(78, 'Quality B', 'Human Resource', 'Division 1', TO_DATE('2024-10-24', 'YYYY-MM-DD'), 'Bangalore', 'Medium', 'Employee Self-Service Portal', 'Other', TO_DATE('2024-07-11', 'YYYY-MM-DD'), 'Running', 'External'),
(79, 'Quality A', 'Information Technology', 'Division 2', TO_DATE('2024-10-25', 'YYYY-MM-DD'), 'Pune', 'High', 'Vendor Management System', 'Business', TO_DATE('2024-08-16', 'YYYY-MM-DD'), 'Registered', 'External'),
(80, 'Quality B', 'Information Technology', 'Division 1', TO_DATE('2025-01-17', 'YYYY-MM-DD'), 'Other', 'Medium', 'Informatica', 'Dealership', TO_DATE('2024-07-11', 'YYYY-MM-DD'), 'Running', 'Internal'),
(81, 'Quality A', 'Other', 'Division 1', TO_DATE('2024-12-31', 'YYYY-MM-DD'), 'Pune', 'High', 'Inner Explorer ', 'Business', TO_DATE('2024-07-11', 'YYYY-MM-DD'), 'Registered', 'Internal');